--;;
drop index if exists idx_note_reference_reference;
--;;
drop index if exists idx_note_reference_note;
--;;
drop table if exists note_reference;
--;;
drop table if exists reference;
--;;
drop table if exists note;
--;;
drop trigger if exists note_moddatetime on note;
--;;
drop index if exists idx_postcard_location;
--;;
drop index if exists idx_postcard_fts_gin;
--;;
drop index if exists idx_postcard_tag_tag_category;
--;;
drop index if exists idx_postcard_tag_postcard;
--;;
drop index if exists idx_postcard_tag_tag;
--;;
drop table if exists postcard_tag;
--;;
drop index if exists idx_postcard_recipient_postcard;
--;;
drop index if exists idx_postcard_recipient_recipient;
--;;
drop table if exists postcard_recipient;
--;;
drop index if exists idx_postcard_series_postcard;
--;;
drop index if exists idx_postcard_series_series;
--;;
drop table if exists postcard_series;
--;;
drop index if exists idx_postcard_publisher_postcard;
--;;
drop index if exists idx_postcard_publisher_publisher;
--;;
drop table if exists postcard_publisher;
--;;
drop index if exists idx_postcard_stamp_postcard;
--;;
drop index if exists idx_postcard_stamp_stamp;
--;;
drop table if exists postcard_stamp;
--;;
drop table if exists slideshow;
--;;
drop trigger if exists postcard_moddatetime on postcard;
--;;
drop table if exists postcard;
--;;
drop table if exists note_image;
--;;
drop index if exists idx_recipient_location;
--;;
drop table if exists recipient;
--;;
drop table if exists series;
--;;
drop table if exists stamp;
--;;
drop index if exists idx_tag_category_category_name;
--;;
drop table if exists tag;
--;;
drop table if exists tag_category;
--;;
drop table if exists publisher;
--;;
drop trigger if exists content_moddatetime on content;
--;;
drop table if exists content;
--;;
drop type if exists stamp_condition;
--;;
drop extension if exists moddatetime;
